# Generated by Django 4.0.4 on 2022-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('course_of_study', models.CharField(max_length=200)),
                ('level_of_study', models.CharField(max_length=50)),
                ('your_whatsapp_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('be_a_member', models.CharField(max_length=100)),
                ('organization_meeting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50)),
                ('potential_executive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('leadership', models.CharField(max_length=100)),
                ('your_hobbies', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Content directorate', 'Content directorate'), ('Graphic design and videography directorate', 'Graphic design and videography directorate'), ('Human Resources directorate', 'Human Resources directorate'), ('Publicity and website directorate', 'Publicity and website directorate'), ('Special duty directorate', 'Special duty directorate'), ('Grant directorate', 'Grant directorate'), ('Finance directorate', 'Finance directorate'), ('Editorial directorate', 'Editorial directorate')], default='Content directorate', max_length=50)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
