# Generated by Django 4.0.4 on 2022-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='be_a_member',
            field=models.CharField(max_length=100, verbose_name='Why do you want to be a member of KLI?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='leadership',
            field=models.CharField(max_length=100, verbose_name='Kindly state any leadership experience you have had. There is no problem if you have none yet.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='level_of_study',
            field=models.CharField(max_length=50, verbose_name='level of study/profession'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_meeting',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='Select one', max_length=50, verbose_name='The organization meeting holds 10am to 12noon every third Saturday of the month. Is that fine with you?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='potential_executive',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='Select one', max_length=50, verbose_name='Every member is a potential executive whenever the need arises. Is that fine with you?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skill',
            field=models.CharField(max_length=100, verbose_name='What skill(s) do you have? There is no problem If you have none yet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='unit',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Content directorate', 'Content directorate'), ('Graphic design and videography directorate', 'Graphic design and videography directorate'), ('Human Resources directorate', 'Human Resources directorate'), ('Publicity and website directorate', 'Publicity and website directorate'), ('Special duty directorate', 'Special duty directorate'), ('Grant directorate', 'Grant directorate'), ('Finance directorate', 'Finance directorate'), ('Editorial directorate', 'Editorial directorate')], default='Select one', max_length=50, verbose_name='Which KLI unit will you like to join?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='your_whatsapp_number',
            field=models.CharField(max_length=50, verbose_name='Your WhatsApp number'),
        ),
    ]
