# Generated by Django 4.0.4 on 2022-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_application_be_a_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='be_a_member',
            field=models.CharField(max_length=100, verbose_name='Why do you want to be a member of KLA?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='unit',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Content directorate', 'Content directorate'), ('Graphic design and videography directorate', 'Graphic design and videography directorate'), ('Human Resources directorate', 'Human Resources directorate'), ('Publicity and website directorate', 'Publicity and website directorate'), ('Special duty directorate', 'Special duty directorate'), ('Grant directorate', 'Grant directorate'), ('Finance directorate', 'Finance directorate'), ('Editorial directorate', 'Editorial directorate')], default='Select one', max_length=50, verbose_name='Which KLA unit will you like to join?'),
        ),
    ]
