# Generated by Django 4.0.4 on 2022-06-02 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_application_be_a_member_alter_application_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='country and state of origin(e.g Nigeria/Oyo state)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Yes', 'Yes'), ('No', 'No'), ('Others', 'Others')], default='Select one', max_length=50, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='be_a_member',
            field=models.CharField(max_length=200, verbose_name='Why do you want to be a member of KLA?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skill',
            field=models.CharField(max_length=200, verbose_name='What skill(s) do you have? There is no problem If you have none yet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='unit',
            field=models.CharField(choices=[('Select one', 'Select one'), ('Content directorate', 'Content directorate'), ('Graphic design and videography directorate', 'Graphic design and videography directorate'), ('Human Resources directorate', 'Human Resources directorate'), ('Publicity and website directorate', 'Publicity and website directorate'), ('Special duty directorate', 'Special duty directorate'), ('Grant directorate', 'Grant directorate'), ('Finance directorate', 'Finance directorate'), ('Editorial directorate', 'Editorial directorate'), ('Others', 'Others')], default='Select one', max_length=50, verbose_name='Which KLA unit will you like to join?'),
        ),
    ]
